return {
{
Key="Settings",Title="Configurações",World="All",Controls={
{Type="Dropdown",Title="Select Weapon"},
{Type="Toggle",Title="Initialize Attack [M1/Melee/Sword]"},
{Type="Slider",Title="Attack Speed",Min=1.0,Max=10.0,Default=1.0},
{Type="Toggle",Title="Bring Mobs"},
{Type="Toggle",Title="Auto Turn on Buso"},
{Type="Toggle",Title="Auto Turn on Race V3"},
{Type="Toggle",Title="Auto Turn on Race V4"},
{Type="Toggle",Title="Auto Turn on Spin Position"},
{Type="Toggle",Title="Turn on Bypass Teleport"},
{Type="Toggle",Title="Panic Mode"},
{Type="Toggle",Title="Anti AFK"},
{Type="Toggle",Title="Remove Hit VFX"},
{Type="Toggle",Title="Remove Death & Respawned VFX"},
{Type="Toggle",Title="Disable Notify"},
{Type="Slider",Title="Stats Value",Min=0.0,Max=1000.0,Default=10.0},
{Type="Toggle",Title="Auto Melee"},
{Type="Toggle",Title="Auto Swords"},
{Type="Toggle",Title="Auto Gun"},
{Type="Toggle",Title="Auto Blox Fruit"},
{Type="Toggle",Title="Auto Defense"},
}},
{
Key="Main",Title="Farm",World="All",Controls={
{Type="Toggle",Title="Auto Farm Level"},
{Type="Toggle",Title="Auto Travel Dressrosa"},
{Type="Toggle",Title="Auto Zou Quest"},
{Type="Toggle",Title="Auto Farm Nearest"},
{Type="Toggle",Title="Auto Factory Raid"},
{Type="Toggle",Title="Auto Pirate Raid"},
{Type="Dropdown",Title="Choose Material"},
{Type="Toggle",Title="Auto Materials"},
{Type="Toggle",Title="Auto Farm Ectoplasm"},
{Type="Toggle",Title="Auto Done Bartilo Quest"},
{Type="Toggle",Title="Auto Done Citizen Quest"},
{Type="Toggle",Title="Auto Training Dummy"},
{Type="Toggle",Title="Auto Collect Berry"},
{Type="Toggle",Title="Auto Collect Chest"},
{Type="Dropdown",Title="Choose Island"},
{Type="Toggle",Title="Auto Mastery Fruits"},
{Type="Toggle",Title="Auto Mastery Gun"},
{Type="Toggle",Title="Auto Mastery All Sword"},
{Type="Toggle",Title="Auto Cake Prince"},
{Type="Toggle",Title="Auto Bones"},
{Type="Toggle",Title="Accept Quests"},
{Type="Toggle",Title="Auto Farm Mirror"},
{Type="Toggle",Title="Auto Soul Reaper [Fully]"},
{Type="Toggle",Title="Auto Random Bones"},
{Type="Toggle",Title="Auto Try Luck Gravestone"},
{Type="Toggle",Title="Auto Pray Gravestone"},
{Type="Toggle",Title="Auto Unlock Dough dungeon"},
{Type="Toggle",Title="Auto Unlock Phoenix dungeon"},
{Type="Toggle",Title="Auto Teleport Barista Cousin"},
{Type="Button",Title="Buy Buso Colors"},
{Type="Toggle",Title="Auto Rainbow Colors"},
{Type="Toggle",Title="Accept Rainbow Quest Faster"},
{Type="Toggle",Title="Auto Farm Observation"},
{Type="Toggle",Title="Auto Observation V2"},
{Type="Toggle",Title="Auto Upgrade Mink V3"},
{Type="Toggle",Title="Auto Upgrade Human V3"},
{Type="Toggle",Title="Auto Upgrade Skypiea V3"},
{Type="Toggle",Title="Auto Upgrade FishMan V3"},
{Type="Toggle",Title="Auto Valkyrie"},
{Type="Toggle",Title="Auto Unlocked Puzzle"},
}},
{
Key="Melee",Title="Estilos de luta",World="All",Controls={
{Type="Toggle",Title="Auto Superhuman"},
{Type="Toggle",Title="Auto DeathStep"},
{Type="Toggle",Title="Auto Sharkman Karate"},
{Type="Toggle",Title="Auto ElectricClaw"},
{Type="Toggle",Title="Auto DragonTalon"},
{Type="Toggle",Title="Auto Godhuman"},
{Type="Toggle",Title="Auto SanguineArt"},
}},
{
Key="Quests",Title="Itens",World="All",Controls={
{Type="Toggle",Title="Auto Elite Quest"},
{Type="Toggle",Title="Stop when got God's Chalice"},
{Type="Toggle",Title="Auto Tushita Sword"},
{Type="Toggle",Title="Auto Yama Sword"},
{Type="Toggle",Title="Auto Get CDK [ Last Quest ]"},
{Type="Toggle",Title="Auto Yama CDK"},
{Type="Toggle",Title="Auto Tushita CDK"},
{Type="Button",Title="Buy Legendary Sword"},
{Type="Button",Title="Buy True Triple Katana Sword"},
{Type="Toggle",Title="Tween to Legendary Sword Dealer"},
{Type="Toggle",Title="Auto Pole V1"},
{Type="Toggle",Title="Auto Pole V2 [Patched]"},
{Type="Toggle",Title="Auto Law Sword"},
{Type="Button",Title="Buy Microchip Law"},
{Type="Button",Title="Start Law Raids"},
{Type="Toggle",Title="Auto Saw Sword"},
{Type="Toggle",Title="Auto Saber Sword"},
{Type="Toggle",Title="Auto Cybrog"},
{Type="Toggle",Title="Auto Usoap's Hat"},
{Type="Toggle",Title="Auto Bisento V2"},
{Type="Toggle",Title="Auto Warden Sword"},
{Type="Toggle",Title="Auto Marine Coat"},
{Type="Toggle",Title="Auto Swan Coat"},
{Type="Toggle",Title="Auto Rengoku Sword"},
{Type="Toggle",Title="Auto Key Rengoku"},
{Type="Toggle",Title="Auto Dragon Trident"},
{Type="Toggle",Title="Auto Long Sword"},
{Type="Toggle",Title="Auto Black Spikey"},
{Type="Toggle",Title="Auto Dark Blade V3"},
{Type="Toggle",Title="Auto Midnight Blade"},
{Type="Toggle",Title="Auto Darkbeard"},
{Type="Toggle",Title="Auto Unlocked DonSwan"},
{Type="Toggle",Title="Auto Swan Glasses"},
{Type="Toggle",Title="Auto Bigmom"},
{Type="Toggle",Title="Auto Canvendish Sword"},
{Type="Toggle",Title="Auto Twin Hooks"},
{Type="Toggle",Title="Auto Serpent Bow"},
{Type="Toggle",Title="Auto Lei Accessory"},
}},
{
Key="Valentine",Title="Valentine",World="All",Controls={
{Type="Toggle",Title="Auto Valentine Gacha"},
}},
{
Key="SeaEvent",Title="Eventos do mar",World="Sea3",Controls={
{Type="Button",Title="Buy Fracments with Spy"},
{Type="Toggle",Title="Auto Teleport Frozen Dimension"},
{Type="Toggle",Title="Auto Drive To Hydra Island"},
{Type="Dropdown",Title="Choose Boats"},
{Type="Button",Title="Buy Boats"},
{Type="Dropdown",Title="Choose Sea Level"},
{Type="Toggle",Title="Auto Sail Boat"},
{Type="Toggle",Title="Auto Shark"},
{Type="Toggle",Title="Auto Piranha"},
{Type="Toggle",Title="Auto Terror Shark"},
{Type="Toggle",Title="Auto Fish Crew Member"},
{Type="Toggle",Title="Auto Haunted Crew Member"},
{Type="Toggle",Title="Auto Attack PirateGrandBrigade"},
{Type="Toggle",Title="Auto Attack Fish Boat"},
{Type="Toggle",Title="Auto Attack Sea Beast"},
{Type="Toggle",Title="Auto Attack Leviathan"},
{Type="Toggle",Title="Auto Find Kitsune Island"},
{Type="Toggle",Title="Auto Teleport to Shrine Actived"},
{Type="Toggle",Title="Auto Collect Azure Ember"},
{Type="Toggle",Title="Auto Trade Azure Ember"},
{Type="Button",Title="Trade Items Azure"},
{Type="Button",Title="Talk with kitsune statue"},
}},
{
Key="Mirage",Title="Mirage e Race V4",World="Sea3",Controls={
{Type="Toggle",Title="Auto Find Mirage Island"},
{Type="Toggle",Title="Auto Tween To Highest Point"},
{Type="Toggle",Title="Auto Collect Gear"},
{Type="Toggle",Title="Change Transparency can see"},
{Type="Toggle",Title="Auto Tween Advanced Fruit Dealer"},
{Type="Toggle",Title="Auto Collect Mirage Chest"},
{Type="Toggle",Title="Auto Skull Guitar"},
{Type="Toggle",Title="Auto Farm Material Skull Guitar"},
{Type="Button",Title="Talk With Stone"},
{Type="Toggle",Title="Auto Look At Moon"},
{Type="Toggle",Title="Auto Pull Lever"},
{Type="Toggle",Title="Auto Train V4"},
{Type="Button",Title="Teleport to Temple of Time"},
{Type="Button",Title="Teleport to Ancient One"},
{Type="Button",Title="Teleport to Ancient Clock"},
{Type="Toggle",Title="Auto Teleport to Race Doors"},
{Type="Toggle",Title="Auto Complete Trial Race"},
{Type="Toggle",Title="Auto Kill Player After Trial"},
}},
{
Key="Drago",Title="Drago Dojo",World="Sea3",Controls={
{Type="Toggle",Title="Auto Dojo Trainer"},
{Type="Toggle",Title="Auto Dragon Hunter"},
{Type="Toggle",Title="Tween To Upgrade Droco Trial"},
{Type="Toggle",Title="Auto Drago (V1)"},
{Type="Toggle",Title="Auto Drago (V2)"},
{Type="Toggle",Title="Auto Drago (V3)"},
{Type="Toggle",Title="Auto Relic Drago Trial"},
{Type="Toggle",Title="Auto Train Drago v4"},
{Type="Toggle",Title="Tween to Drago Trials"},
{Type="Toggle",Title="Swap Drago Race"},
{Type="Toggle",Title="Upgrade Dragon Talon With Uzoth"},
}},
{
Key="Prehistoric",Title="Prehistoric",World="Sea3",Controls={
{Type="Toggle",Title="Auto Craft Volcanic Magnet"},
{Type="Button",Title="Craft Volcanic Magnet"},
{Type="Toggle",Title="Auto Find Prehistoric Island"},
{Type="Toggle",Title="Auto Patch Prehistoric Event"},
{Type="Toggle",Title="Auto Collect Dino Bones"},
{Type="Toggle",Title="Auto Collect Dragon Eggs"},
{Type="Toggle",Title="Auto Reset When Complete Volcano"},
}},
{
Key="Raids",Title="Raids",World="Sea2Sea3",Controls={
{Type="Dropdown",Title="Select Chip"},
{Type="Toggle",Title="Auto Select Dungeon Chip"},
{Type="Button",Title="Buy Dungeon Chips [Beli]"},
{Type="Button",Title="Buy Dungeon Chips [Devil Fruit]"},
{Type="Toggle",Title="Auto Start Raid"},
{Type="Toggle",Title="Teleport To Lab"},
{Type="Toggle",Title="Auto Complete Raid [Safety]"},
{Type="Toggle",Title="Kill Aura"},
{Type="Toggle",Title="Auto Next Island"},
{Type="Toggle",Title="Auto Awakening"},
}},
{
Key="Combat",Title="Combate e PVP",World="All",Controls={
{Type="Dropdown",Title="Choose Players"},
{Type="Toggle",Title="Teleport to choose players"},
{Type="Toggle",Title="Spectate Choose Players"},
{Type="Dropdown",Title="Choose Aim Method"},
{Type="Toggle",Title="Aimbot Method Skills"},
{Type="Toggle",Title="Aimbot Camera Closet Players"},
{Type="Toggle",Title="Instance Mink V3 [ INF ]"},
{Type="Toggle",Title="Instance Energy [ INF ]"},
{Type="Toggle",Title="Instance Soru [ INF ]"},
{Type="Toggle",Title="Instance Observation Range [ INF ]"},
{Type="Toggle",Title="Ignore Same Teams"},
{Type="Toggle",Title="Accept Allies"},
{Type="Toggle",Title="Esp Berries"},
{Type="Toggle",Title="Esp Players"},
{Type="Toggle",Title="Esp Chests"},
{Type="Toggle",Title="Esp Fruits"},
{Type="Toggle",Title="Esp Island Location"},
{Type="Toggle",Title="Esp Flower"},
{Type="Toggle",Title="Esp Legendary Sword"},
{Type="Toggle",Title="Esp Aura Colour Dealers"},
{Type="Toggle",Title="Esp Gears"},
{Type="Toggle",Title="Esp SeaEvent Island"},
{Type="Toggle",Title="Esp Advanced Fruits Dealer"},
}},
{
Key="Travel",Title="Viagem",World="All",Controls={
{Type="Button",Title="Travel East Blue (World 1)"},
{Type="Button",Title="Travel Dressrosa (World 2)"},
{Type="Button",Title="Travel Zou (World 3)"},
{Type="Dropdown",Title="Select Travelling"},
{Type="Toggle",Title="Auto Travel"},
{Type="Dropdown",Title="Select Portal"},
{Type="Button",Title="requestEntrance"},
{Type="Dropdown",Title="Select NPCs"},
{Type="Toggle",Title="Auto Tween to NPCs"},
}},
{
Key="Fruit",Title="Frutas",World="All",Controls={
{Type="Dropdown",Title="Select Fruit Stock"},
{Type="Button",Title="Buy Basic Stock"},
{Type="Dropdown",Title="Select Mirage Fruit"},
{Type="Button",Title="Buy Mirage Stock"},
{Type="Toggle",Title="Auto Random Fruit"},
{Type="Toggle",Title="Auto Drop Fruit"},
{Type="Toggle",Title="Auto Store Fruit"},
{Type="Toggle",Title="Auto Tween to Fruit"},
{Type="Toggle",Title="Auto Collect Fruit"},
}},
{
Key="Shop",Title="Loja",World="All",Controls={
{Type="Button",Title="Buy Buso"},
{Type="Button",Title="Buy Geppo"},
{Type="Button",Title="Buy Soru"},
{Type="Button",Title="Buy Ken"},
{Type="Button",Title="Buy Black Leg"},
{Type="Button",Title="Buy Electro"},
{Type="Button",Title="Buy Fishman Karate"},
{Type="Button",Title="Buy DragonClaw"},
{Type="Button",Title="Buy Superhuman"},
{Type="Button",Title="Buy Death Step"},
{Type="Button",Title="Buy Sharkman Karate"},
{Type="Button",Title="Buy ElectricClaw"},
{Type="Button",Title="Buy DragonTalon"},
{Type="Button",Title="Buy Godhuman"},
{Type="Button",Title="Buy SanguineArt"},
{Type="Button",Title="Buy Tomoe Ring"},
{Type="Button",Title="Buy Black Cape"},
{Type="Button",Title="Buy Swordsman Hat"},
{Type="Button",Title="Buy Bizarre Rifle"},
{Type="Button",Title="Buy Ghoul Mask"},
{Type="Button",Title="Craft Dragonheart"},
{Type="Button",Title="Craft Dragonstorm"},
{Type="Button",Title="Craft DinoHood"},
{Type="Button",Title="Craft SharkTooth"},
{Type="Button",Title="Craft TerrorJaw"},
{Type="Button",Title="Craft SharkAnchor"},
{Type="Button",Title="Craft LeviathanCrown"},
{Type="Button",Title="Craft LeviathanShield"},
{Type="Button",Title="Craft LeviathanBoat"},
{Type="Button",Title="Craft LegendaryScroll"},
{Type="Button",Title="Craft MythicalScroll"},
{Type="Button",Title="Buy Cutlass"},
{Type="Button",Title="Buy Katana"},
{Type="Button",Title="Buy Iron Mace"},
{Type="Button",Title="Buy Duel Katana"},
{Type="Button",Title="Buy Triple Katana"},
{Type="Button",Title="Buy Pipe"},
{Type="Button",Title="Buy Dual-Headed Blade"},
{Type="Button",Title="Buy Bisento"},
{Type="Button",Title="Buy Soul Cane"},
{Type="Button",Title="Buy Slingshot"},
{Type="Button",Title="Buy Musket"},
{Type="Button",Title="Buy Dual Flintlock"},
{Type="Button",Title="Buy Flintlock"},
{Type="Button",Title="Buy Refined Flintlock"},
{Type="Button",Title="Buy Cannon"},
{Type="Button",Title="Buy Kabucha"},
{Type="Button",Title="Buy Refund Stats"},
{Type="Button",Title="Buy Reroll Race"},
{Type="Button",Title="Buy Ghoul Race (2.5k)"},
{Type="Button",Title="Buy Cyborg Race (2.5k)"},
}},
{
Key="Misc",Title="Outros",World="All",Controls={
{Type="Button",Title="Rejoin Server"},
{Type="Button",Title="Hop Server"},
{Type="Button",Title="Hop to Lowest Players"},
{Type="Button",Title="Hop to Lowest Pings Server"},
{Type="Button",Title="Teleport [Job ID]"},
{Type="Button",Title="Copy JobID"},
{Type="Button",Title="Open Awakenings Expert"},
{Type="Button",Title="Open Title Selection"},
{Type="Toggle",Title="Disable Chat GUI"},
{Type="Toggle",Title="Disable Leader Board GUI"},
{Type="Button",Title="Set Pirate Team"},
{Type="Button",Title="Set Marine Team"},
{Type="Toggle",Title="Unlock All Portals"},
{Type="Dropdown",Title="Select Haki States"},
{Type="Button",Title="ChangeBusoStage"},
{Type="Toggle",Title="Turn on RTX Mode"},
{Type="Button",Title="Turn on Fast Mode"},
{Type="Button",Title="Turn on Low CPU"},
{Type="Button",Title="Turn on increase Boats"},
{Type="Button",Title="Remove Sky Fog"},
{Type="Button",Title="Rain Fruits (Client)"},
{Type="Toggle",Title="Turn on Full Bright"},
{Type="Dropdown",Title="Select Time"},
{Type="Toggle",Title="Turn on Time"},
{Type="Toggle",Title="Turn on Walk on Water"},
{Type="Toggle",Title="Turn on Ice Walk"},
}},
}
