return {
{
Key="Settings",Title="Configurações",World="All",Controls={
{Type="Dropdown",Title="Select Weapon",World="All"},
{Type="Toggle",Title="Initialize Attack [M1/Melee/Sword]",World="All"},
{Type="Slider",Title="Attack Speed",World="All",Min=1.0,Max=10.0,Default=1.0},
{Type="Toggle",Title="Bring Mobs",World="All"},
{Type="Toggle",Title="Auto Turn on Buso",World="All"},
{Type="Toggle",Title="Auto Turn on Race V3",World="All"},
{Type="Toggle",Title="Auto Turn on Race V4",World="All"},
{Type="Toggle",Title="Auto Turn on Spin Position",World="All"},
{Type="Toggle",Title="Turn on Bypass Teleport",World="All"},
{Type="Toggle",Title="Panic Mode",World="All"},
{Type="Toggle",Title="Anti AFK",World="All"},
{Type="Toggle",Title="Remove Hit VFX",World="All"},
{Type="Toggle",Title="Remove Death & Respawned VFX",World="All"},
{Type="Toggle",Title="Disable Notify",World="All"},
{Type="Slider",Title="Stats Value",World="All",Min=0.0,Max=1000.0,Default=10.0},
{Type="Toggle",Title="Auto Melee",World="All"},
{Type="Toggle",Title="Auto Swords",World="All"},
{Type="Toggle",Title="Auto Gun",World="All"},
{Type="Toggle",Title="Auto Blox Fruit",World="All"},
{Type="Toggle",Title="Auto Defense",World="All"},
}},
{
Key="Main",Title="Farm",World="All",Controls={
{Type="Toggle",Title="Auto Farm Level",World="All"},
{Type="Toggle",Title="Auto Travel Dressrosa",World="Sea1"},
{Type="Toggle",Title="Auto Zou Quest",World="Sea2"},
{Type="Toggle",Title="Auto Farm Nearest",World="All"},
{Type="Toggle",Title="Auto Factory Raid",World="Sea2"},
{Type="Toggle",Title="Auto Pirate Raid",World="Sea3"},
{Type="Dropdown",Title="Choose Material",World="All"},
{Type="Toggle",Title="Auto Materials",World="All"},
{Type="Toggle",Title="Auto Farm Ectoplasm",World="Sea2"},
{Type="Toggle",Title="Auto Done Bartilo Quest",World="Sea2"},
{Type="Toggle",Title="Auto Done Citizen Quest",World="Sea3"},
{Type="Toggle",Title="Auto Training Dummy",World="Sea3"},
{Type="Toggle",Title="Auto Collect Berry",World="Sea3"},
{Type="Toggle",Title="Auto Collect Chest",World="All"},
{Type="Dropdown",Title="Choose Island",World="All"},
{Type="Toggle",Title="Auto Mastery Fruits",World="All"},
{Type="Toggle",Title="Auto Mastery Gun",World="All"},
{Type="Toggle",Title="Auto Mastery All Sword",World="All"},
{Type="Toggle",Title="Auto Cake Prince",World="Sea3"},
{Type="Toggle",Title="Auto Bones",World="Sea3"},
{Type="Toggle",Title="Accept Quests",World="All"},
{Type="Toggle",Title="Auto Farm Mirror",World="Sea3"},
{Type="Toggle",Title="Auto Soul Reaper [Fully]",World="Sea3"},
{Type="Toggle",Title="Auto Random Bones",World="Sea3"},
{Type="Toggle",Title="Auto Try Luck Gravestone",World="Sea3"},
{Type="Toggle",Title="Auto Pray Gravestone",World="Sea3"},
{Type="Toggle",Title="Auto Unlock Dough dungeon",World="Sea3"},
{Type="Toggle",Title="Auto Unlock Phoenix dungeon",World="Sea2Sea3"},
{Type="Toggle",Title="Auto Teleport Barista Cousin",World="Sea3"},
{Type="Button",Title="Buy Buso Colors",World="Sea3"},
{Type="Toggle",Title="Auto Rainbow Colors",World="Sea3"},
{Type="Toggle",Title="Accept Rainbow Quest Faster",World="Sea3"},
{Type="Toggle",Title="Auto Farm Observation",World="All"},
{Type="Toggle",Title="Auto Observation V2",World="Sea2"},
{Type="Toggle",Title="Auto Upgrade Mink V3",World="Sea2"},
{Type="Toggle",Title="Auto Upgrade Human V3",World="Sea2"},
{Type="Toggle",Title="Auto Upgrade Skypiea V3",World="Sea2"},
{Type="Toggle",Title="Auto Upgrade FishMan V3",World="Sea2"},
{Type="Toggle",Title="Auto Valkyrie",World="Sea3"},
{Type="Toggle",Title="Auto Unlocked Puzzle",World="Sea3"},
}},
{
Key="Melee",Title="Estilos de luta",World="All",Controls={
{Type="Toggle",Title="Auto Superhuman",World="All"},
{Type="Toggle",Title="Auto DeathStep",World="All"},
{Type="Toggle",Title="Auto Sharkman Karate",World="All"},
{Type="Toggle",Title="Auto ElectricClaw",World="All"},
{Type="Toggle",Title="Auto DragonTalon",World="All"},
{Type="Toggle",Title="Auto Godhuman",World="All"},
{Type="Toggle",Title="Auto SanguineArt",World="All"},
}},
{
Key="Quests",Title="Itens",World="All",Controls={
{Type="Toggle",Title="Auto Elite Quest",World="Sea3"},
{Type="Toggle",Title="Stop when got God's Chalice",World="Sea3"},
{Type="Toggle",Title="Auto Tushita Sword",World="Sea3"},
{Type="Toggle",Title="Auto Yama Sword",World="Sea3"},
{Type="Toggle",Title="Auto Get CDK [ Last Quest ]",World="Sea3"},
{Type="Toggle",Title="Auto Yama CDK",World="Sea3"},
{Type="Toggle",Title="Auto Tushita CDK",World="Sea3"},
{Type="Button",Title="Buy Legendary Sword",World="Sea2"},
{Type="Button",Title="Buy True Triple Katana Sword",World="Sea2"},
{Type="Toggle",Title="Tween to Legendary Sword Dealer",World="Sea2"},
{Type="Toggle",Title="Auto Pole V1",World="Sea1"},
{Type="Toggle",Title="Auto Pole V2 [Patched]",World="Sea2"},
{Type="Toggle",Title="Auto Law Sword",World="Sea2"},
{Type="Button",Title="Buy Microchip Law",World="Sea2"},
{Type="Button",Title="Start Law Raids",World="Sea2"},
{Type="Toggle",Title="Auto Saw Sword",World="Sea1"},
{Type="Toggle",Title="Auto Saber Sword",World="Sea1"},
{Type="Toggle",Title="Auto Cybrog",World="Sea1"},
{Type="Toggle",Title="Auto Usoap's Hat",World="Sea1"},
{Type="Toggle",Title="Auto Bisento V2",World="Sea1"},
{Type="Toggle",Title="Auto Warden Sword",World="Sea1"},
{Type="Toggle",Title="Auto Marine Coat",World="Sea1"},
{Type="Toggle",Title="Auto Swan Coat",World="Sea1"},
{Type="Toggle",Title="Auto Rengoku Sword",World="Sea2"},
{Type="Toggle",Title="Auto Key Rengoku",World="Sea2"},
{Type="Toggle",Title="Auto Dragon Trident",World="Sea2"},
{Type="Toggle",Title="Auto Long Sword",World="Sea2"},
{Type="Toggle",Title="Auto Black Spikey",World="Sea3"},
{Type="Toggle",Title="Auto Dark Blade V3",World="Sea3"},
{Type="Toggle",Title="Auto Midnight Blade",World="Sea2"},
{Type="Toggle",Title="Auto Darkbeard",World="Sea2"},
{Type="Toggle",Title="Auto Unlocked DonSwan",World="Sea2"},
{Type="Toggle",Title="Auto Swan Glasses",World="Sea2"},
{Type="Toggle",Title="Auto Bigmom",World="Sea3"},
{Type="Toggle",Title="Auto Canvendish Sword",World="Sea3"},
{Type="Toggle",Title="Auto Twin Hooks",World="Sea3"},
{Type="Toggle",Title="Auto Serpent Bow",World="Sea3"},
{Type="Toggle",Title="Auto Lei Accessory",World="Sea3"},
}},
{
Key="Valentine",Title="Valentine",World="All",Controls={
{Type="Toggle",Title="Auto Valentine Gacha",World="All"},
}},
{
Key="SeaEvent",Title="Eventos do mar",World="Sea3",Controls={
{Type="Button",Title="Buy Fracments with Spy",World="All"},
{Type="Toggle",Title="Auto Teleport Frozen Dimension",World="All"},
{Type="Toggle",Title="Auto Drive To Hydra Island",World="All"},
{Type="Dropdown",Title="Choose Boats",World="All"},
{Type="Button",Title="Buy Boats",World="All"},
{Type="Dropdown",Title="Choose Sea Level",World="All"},
{Type="Toggle",Title="Auto Sail Boat",World="All"},
{Type="Toggle",Title="Auto Shark",World="All"},
{Type="Toggle",Title="Auto Piranha",World="All"},
{Type="Toggle",Title="Auto Terror Shark",World="All"},
{Type="Toggle",Title="Auto Fish Crew Member",World="All"},
{Type="Toggle",Title="Auto Haunted Crew Member",World="All"},
{Type="Toggle",Title="Auto Attack PirateGrandBrigade",World="All"},
{Type="Toggle",Title="Auto Attack Fish Boat",World="All"},
{Type="Toggle",Title="Auto Attack Sea Beast",World="All"},
{Type="Toggle",Title="Auto Attack Leviathan",World="All"},
{Type="Toggle",Title="Auto Find Kitsune Island",World="All"},
{Type="Toggle",Title="Auto Teleport to Shrine Actived",World="All"},
{Type="Toggle",Title="Auto Collect Azure Ember",World="All"},
{Type="Toggle",Title="Auto Trade Azure Ember",World="All"},
{Type="Button",Title="Trade Items Azure",World="All"},
{Type="Button",Title="Talk with kitsune statue",World="All"},
}},
{
Key="Mirage",Title="Mirage e Race V4",World="Sea3",Controls={
{Type="Toggle",Title="Auto Find Mirage Island",World="All"},
{Type="Toggle",Title="Auto Tween To Highest Point",World="All"},
{Type="Toggle",Title="Auto Collect Gear",World="All"},
{Type="Toggle",Title="Change Transparency can see",World="All"},
{Type="Toggle",Title="Auto Tween Advanced Fruit Dealer",World="All"},
{Type="Toggle",Title="Auto Collect Mirage Chest",World="All"},
{Type="Toggle",Title="Auto Skull Guitar",World="All"},
{Type="Toggle",Title="Auto Farm Material Skull Guitar",World="All"},
{Type="Button",Title="Talk With Stone",World="All"},
{Type="Toggle",Title="Auto Look At Moon",World="All"},
{Type="Toggle",Title="Auto Pull Lever",World="All"},
{Type="Toggle",Title="Auto Train V4",World="All"},
{Type="Button",Title="Teleport to Temple of Time",World="All"},
{Type="Button",Title="Teleport to Ancient One",World="All"},
{Type="Button",Title="Teleport to Ancient Clock",World="All"},
{Type="Toggle",Title="Auto Teleport to Race Doors",World="All"},
{Type="Toggle",Title="Auto Complete Trial Race",World="All"},
{Type="Toggle",Title="Auto Kill Player After Trial",World="All"},
}},
{
Key="Drago",Title="Drago Dojo",World="Sea3",Controls={
{Type="Toggle",Title="Auto Dojo Trainer",World="All"},
{Type="Toggle",Title="Auto Dragon Hunter",World="All"},
{Type="Toggle",Title="Tween To Upgrade Droco Trial",World="All"},
{Type="Toggle",Title="Auto Drago (V1)",World="All"},
{Type="Toggle",Title="Auto Drago (V2)",World="All"},
{Type="Toggle",Title="Auto Drago (V3)",World="All"},
{Type="Toggle",Title="Auto Relic Drago Trial",World="All"},
{Type="Toggle",Title="Auto Train Drago v4",World="All"},
{Type="Toggle",Title="Tween to Drago Trials",World="All"},
{Type="Toggle",Title="Swap Drago Race",World="All"},
{Type="Toggle",Title="Upgrade Dragon Talon With Uzoth",World="All"},
}},
{
Key="Prehistoric",Title="Prehistoric",World="Sea3",Controls={
{Type="Toggle",Title="Auto Craft Volcanic Magnet",World="All"},
{Type="Button",Title="Craft Volcanic Magnet",World="All"},
{Type="Toggle",Title="Auto Find Prehistoric Island",World="All"},
{Type="Toggle",Title="Auto Patch Prehistoric Event",World="All"},
{Type="Toggle",Title="Auto Collect Dino Bones",World="All"},
{Type="Toggle",Title="Auto Collect Dragon Eggs",World="All"},
{Type="Toggle",Title="Auto Reset When Complete Volcano",World="All"},
}},
{
Key="Raids",Title="Raids",World="Sea2Sea3",Controls={
{Type="Dropdown",Title="Select Chip",World="All"},
{Type="Toggle",Title="Auto Select Dungeon Chip",World="All"},
{Type="Button",Title="Buy Dungeon Chips [Beli]",World="All"},
{Type="Button",Title="Buy Dungeon Chips [Devil Fruit]",World="All"},
{Type="Toggle",Title="Auto Start Raid",World="All"},
{Type="Toggle",Title="Teleport To Lab",World="All"},
{Type="Toggle",Title="Auto Complete Raid [Safety]",World="All"},
{Type="Toggle",Title="Kill Aura",World="All"},
{Type="Toggle",Title="Auto Next Island",World="All"},
{Type="Toggle",Title="Auto Awakening",World="All"},
}},
{
Key="Combat",Title="Combate e PVP",World="All",Controls={
{Type="Dropdown",Title="Choose Players",World="All"},
{Type="Toggle",Title="Teleport to choose players",World="All"},
{Type="Toggle",Title="Spectate Choose Players",World="All"},
{Type="Dropdown",Title="Choose Aim Method",World="All"},
{Type="Toggle",Title="Aimbot Method Skills",World="All"},
{Type="Toggle",Title="Aimbot Camera Closet Players",World="All"},
{Type="Toggle",Title="Instance Mink V3 [ INF ]",World="All"},
{Type="Toggle",Title="Instance Energy [ INF ]",World="All"},
{Type="Toggle",Title="Instance Soru [ INF ]",World="All"},
{Type="Toggle",Title="Instance Observation Range [ INF ]",World="All"},
{Type="Toggle",Title="Ignore Same Teams",World="All"},
{Type="Toggle",Title="Accept Allies",World="All"},
{Type="Toggle",Title="Esp Berries",World="Sea3"},
{Type="Toggle",Title="Esp Players",World="All"},
{Type="Toggle",Title="Esp Chests",World="All"},
{Type="Toggle",Title="Esp Fruits",World="All"},
{Type="Toggle",Title="Esp Island Location",World="All"},
{Type="Toggle",Title="Esp Flower",World="Sea2"},
{Type="Toggle",Title="Esp Legendary Sword",World="Sea2"},
{Type="Toggle",Title="Esp Aura Colour Dealers",World="Sea2Sea3"},
{Type="Toggle",Title="Esp Gears",World="Sea3"},
{Type="Toggle",Title="Esp SeaEvent Island",World="Sea3"},
{Type="Toggle",Title="Esp Advanced Fruits Dealer",World="Sea3"},
}},
{
Key="Travel",Title="Viagem",World="All",Controls={
{Type="Button",Title="Travel East Blue (World 1)",World="All"},
{Type="Button",Title="Travel Dressrosa (World 2)",World="All"},
{Type="Button",Title="Travel Zou (World 3)",World="All"},
{Type="Dropdown",Title="Select Travelling",World="All"},
{Type="Toggle",Title="Auto Travel",World="All"},
{Type="Dropdown",Title="Select Portal",World="All"},
{Type="Button",Title="requestEntrance",World="All"},
{Type="Dropdown",Title="Select NPCs",World="All"},
{Type="Toggle",Title="Auto Tween to NPCs",World="All"},
}},
{
Key="Fruit",Title="Frutas",World="All",Controls={
{Type="Dropdown",Title="Select Fruit Stock",World="All"},
{Type="Button",Title="Refresh Fruit Stock",World="All"},
{Type="Button",Title="Buy Basic Stock",World="All"},
{Type="Dropdown",Title="Select Mirage Fruit",World="All"},
{Type="Button",Title="Buy Mirage Stock",World="All"},
{Type="Dropdown",Title="Select Fruit Sniper",World="All"},
{Type="Toggle",Title="Auto Buy Selected Fruit",World="All"},
{Type="Toggle",Title="Auto Random Fruit",World="All"},
{Type="Button",Title="Random Fruit Now",World="All"},
{Type="Toggle",Title="Auto Drop Fruit",World="All"},
{Type="Toggle",Title="Auto Store Fruit",World="All"},
{Type="Toggle",Title="Auto Tween to Fruit",World="All"},
{Type="Toggle",Title="Auto Collect Fruit",World="All"},
}},
{
Key="Shop",Title="Loja",World="All",Controls={
{Type="Button",Title="Buy Buso",World="All"},
{Type="Button",Title="Buy Geppo",World="All"},
{Type="Button",Title="Buy Soru",World="All"},
{Type="Button",Title="Buy Ken",World="All"},
{Type="Button",Title="Buy Black Leg",World="All"},
{Type="Button",Title="Buy Electro",World="All"},
{Type="Button",Title="Buy Fishman Karate",World="All"},
{Type="Button",Title="Buy DragonClaw",World="All"},
{Type="Button",Title="Buy Superhuman",World="All"},
{Type="Button",Title="Buy Death Step",World="All"},
{Type="Button",Title="Buy Sharkman Karate",World="All"},
{Type="Button",Title="Buy ElectricClaw",World="All"},
{Type="Button",Title="Buy DragonTalon",World="All"},
{Type="Button",Title="Buy Godhuman",World="All"},
{Type="Button",Title="Buy SanguineArt",World="All"},
{Type="Button",Title="Buy Tomoe Ring",World="All"},
{Type="Button",Title="Buy Black Cape",World="All"},
{Type="Button",Title="Buy Swordsman Hat",World="All"},
{Type="Button",Title="Buy Bizarre Rifle",World="Sea2"},
{Type="Button",Title="Buy Ghoul Mask",World="Sea2"},
{Type="Button",Title="Craft Dragonheart",World="Sea3"},
{Type="Button",Title="Craft Dragonstorm",World="Sea3"},
{Type="Button",Title="Craft DinoHood",World="Sea3"},
{Type="Button",Title="Craft SharkTooth",World="Sea3"},
{Type="Button",Title="Craft TerrorJaw",World="Sea3"},
{Type="Button",Title="Craft SharkAnchor",World="Sea3"},
{Type="Button",Title="Craft LeviathanCrown",World="Sea3"},
{Type="Button",Title="Craft LeviathanShield",World="Sea3"},
{Type="Button",Title="Craft LeviathanBoat",World="Sea3"},
{Type="Button",Title="Craft LegendaryScroll",World="Sea3"},
{Type="Button",Title="Craft MythicalScroll",World="Sea3"},
{Type="Button",Title="Buy Cutlass",World="All"},
{Type="Button",Title="Buy Katana",World="All"},
{Type="Button",Title="Buy Iron Mace",World="All"},
{Type="Button",Title="Buy Duel Katana",World="All"},
{Type="Button",Title="Buy Triple Katana",World="All"},
{Type="Button",Title="Buy Pipe",World="All"},
{Type="Button",Title="Buy Dual-Headed Blade",World="All"},
{Type="Button",Title="Buy Bisento",World="All"},
{Type="Button",Title="Buy Soul Cane",World="All"},
{Type="Button",Title="Buy Slingshot",World="All"},
{Type="Button",Title="Buy Musket",World="All"},
{Type="Button",Title="Buy Dual Flintlock",World="All"},
{Type="Button",Title="Buy Flintlock",World="All"},
{Type="Button",Title="Buy Refined Flintlock",World="All"},
{Type="Button",Title="Buy Cannon",World="All"},
{Type="Button",Title="Buy Kabucha",World="All"},
{Type="Button",Title="Buy Refund Stats",World="All"},
{Type="Button",Title="Buy Reroll Race",World="All"},
{Type="Button",Title="Buy Ghoul Race (2.5k)",World="Sea2"},
{Type="Button",Title="Buy Cyborg Race (2.5k)",World="All"},
}},
{
Key="Misc",Title="Outros",World="All",Controls={
{Type="Button",Title="Rejoin Server",World="All"},
{Type="Button",Title="Hop Server",World="All"},
{Type="Button",Title="Hop to Lowest Players",World="All"},
{Type="Button",Title="Hop to Lowest Pings Server",World="All"},
{Type="Input",Title="JobID",World="All"},
{Type="Button",Title="Teleport [Job ID]",World="All"},
{Type="Button",Title="Copy JobID",World="All"},
{Type="Button",Title="Open Awakenings Expert",World="All"},
{Type="Button",Title="Open Title Selection",World="All"},
{Type="Toggle",Title="Disable Chat GUI",World="All"},
{Type="Toggle",Title="Disable Leader Board GUI",World="All"},
{Type="Button",Title="Set Pirate Team",World="All"},
{Type="Button",Title="Set Marine Team",World="All"},
{Type="Toggle",Title="Unlock All Portals",World="All"},
{Type="Dropdown",Title="Select Haki States",World="All"},
{Type="Button",Title="ChangeBusoStage",World="All"},
{Type="Toggle",Title="Turn on RTX Mode",World="All"},
{Type="Button",Title="Turn on Fast Mode",World="All"},
{Type="Button",Title="Turn on Low CPU",World="All"},
{Type="Button",Title="Turn on increase Boats",World="Sea3"},
{Type="Button",Title="Remove Sky Fog",World="All"},
{Type="Button",Title="Rain Fruits (Client)",World="All"},
{Type="Toggle",Title="Turn on Full Bright",World="All"},
{Type="Dropdown",Title="Select Time",World="All"},
{Type="Toggle",Title="Turn on Time",World="All"},
{Type="Toggle",Title="Turn on Walk on Water",World="All"},
{Type="Toggle",Title="Turn on Ice Walk",World="All"},
}},
}
